/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding/complete'
import { Route as OnboardingHouseholdRouteImport } from './routes/onboarding/household'
import { Route as OnboardingInventoryRouteImport } from './routes/onboarding/inventory'
import { Route as OnboardingKitchenRouteImport } from './routes/onboarding/kitchen'
import { Route as OnboardingProfileRouteImport } from './routes/onboarding/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingHouseholdRoute = OnboardingHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingInventoryRoute = OnboardingInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingKitchenRoute = OnboardingKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileRoute = OnboardingProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OnboardingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/household': typeof OnboardingHouseholdRoute
  '/onboarding/inventory': typeof OnboardingInventoryRoute
  '/onboarding/kitchen': typeof OnboardingKitchenRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/household': typeof OnboardingHouseholdRoute
  '/onboarding/inventory': typeof OnboardingInventoryRoute
  '/onboarding/kitchen': typeof OnboardingKitchenRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/register': typeof RegisterRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/household': typeof OnboardingHouseholdRoute
  '/onboarding/inventory': typeof OnboardingInventoryRoute
  '/onboarding/kitchen': typeof OnboardingKitchenRoute
  '/onboarding/profile': typeof OnboardingProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/onboarding/complete'
    | '/onboarding/household'
    | '/onboarding/inventory'
    | '/onboarding/kitchen'
    | '/onboarding/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/onboarding/complete'
    | '/onboarding/household'
    | '/onboarding/inventory'
    | '/onboarding/kitchen'
    | '/onboarding/profile'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/onboarding/complete'
    | '/onboarding/household'
    | '/onboarding/inventory'
    | '/onboarding/kitchen'
    | '/onboarding/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/household': {
      id: '/onboarding/household'
      path: '/household'
      fullPath: '/onboarding/household'
      preLoaderRoute: typeof OnboardingHouseholdRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/inventory': {
      id: '/onboarding/inventory'
      path: '/inventory'
      fullPath: '/onboarding/inventory'
      preLoaderRoute: typeof OnboardingInventoryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/kitchen': {
      id: '/onboarding/kitchen'
      path: '/kitchen'
      fullPath: '/onboarding/kitchen'
      preLoaderRoute: typeof OnboardingKitchenRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/profile': {
      id: '/onboarding/profile'
      path: '/profile'
      fullPath: '/onboarding/profile'
      preLoaderRoute: typeof OnboardingProfileRouteImport
      parentRoute: typeof OnboardingRoute
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingHouseholdRoute: typeof OnboardingHouseholdRoute
  OnboardingInventoryRoute: typeof OnboardingInventoryRoute
  OnboardingKitchenRoute: typeof OnboardingKitchenRoute
  OnboardingProfileRoute: typeof OnboardingProfileRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingHouseholdRoute: OnboardingHouseholdRoute,
  OnboardingInventoryRoute: OnboardingInventoryRoute,
  OnboardingKitchenRoute: OnboardingKitchenRoute,
  OnboardingProfileRoute: OnboardingProfileRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
